### ISSUE TITLE
RunTime Exception:Matrix is singular

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#174] opened 2017-04-14 18:45 UTC
Hi Hai,
I am constantly running into this issue. 
I have tried normalizing the data aswell but same issue. 
`[main] INFO smile.manifold.LLE - LLE: 2 connected components, largest one has 986 samples.
Exception in thread "main" java.lang.RuntimeException: Matrix is singular.
	at smile.math.matrix.LUDecomposition.solve(LUDecomposition.java:254)
	at smile.manifold.LLE.<init>(LLE.java:178)
	at com.dimensionality.reduction.LLELearner.learn(LLELearner.java:67)
	at com..dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:85)
	at com.common.ModelingEngine.main(ModelingEngine.java:81)`

**Comment by haifengl** [comment] 2017-04-14 19:15
Can you share your data to debug? BTW, if the matrix is singular indeed, it is not the problem with the algorithm. Besides, do you have duplicated samples in this data? It may cause this problem. Thanks!

**Comment by haifengl** [comment] 2017-04-18 14:19
As this was caused by duplicated samples, I will close this ticket. Thanks!

**Closed by haifengl** 2017-04-18 14:19 UTC
