### ISSUE TITLE
NullPointerException inferring on dataset without inference column

### ISSUE THREAD

**Issue by cnuernber** [haifengl/smile#554] opened 2020-06-05 18:37 UTC
**Describe the bug**
Getting an NPE exception during inference.

**Expected behavior**
No NPE.

**Actual behavior**
Stack trace:
```console
           StructType.java:   81  smile.data.type.StructType/fieldIndex
             Variable.java:  129  smile.data.formula.Variable/bind
              Formula.java:  219  smile.data.formula.Formula/bind
              Formula.java:  320  smile.data.formula.Formula/x
    GradientTreeBoost.java:  312  smile.regression.GradientTreeBoost/predict
```
Digging into this Formula::x attempts to bind to the entire schema and then trims out the target:
Formula/x:
```java
 bind(t.schema(), false);
``` 
Formula/bind
```java
if (schema != null && !forced) {
            return schema;
        }

        if (response != null) response.bind(inputSchema); //<--this line throws during inference
        Arrays.stream(predictors).forEach(term -> term.bind(inputSchema));
```

**Code snippet**
```clojure
user> (require '[tech.ml.dataset :as ds])
nil
user> (def ds (ds/->dataset [{:a 1 :b 2} {:a 2 :b 3}]))
#'user/ds
user> (def formula (smile.data.formula.Formula. "b"))
#'user/formula
user> (def df (ds/dataset->smile-dataframe ds))
#'user/df
user> df
[a: long, b: long]
+---+---+
|  a|  b|
+---+---+
|  1|  2|
|  2|  3|
+---+---+
user> (.x formula df)
[a: long]
+---+
|  a|
+---+
|  1|
|  2|
+---+
user> (.x formula (.get df 0))
#object[smile.data.formula.Formula$2 0x240ccdd1 "{\n  a: 1\n}"]
user> (def df-minus-b (ds/dataset->smile-dataframe (ds/remove-column ds :b)))
#'user/df-minus-b
user> df-minus-b
[a: long]
+---+
|  a|
+---+
|  1|
|  2|
+---+
user> (.x formula df-minus-b)
Execution error (NullPointerException) at smile.data.type.StructType/fieldIndex (StructType.java:81).
null
```
The actual pathway here is to train the regressor on a dataset, save it out using serialization, load it 
in, and then attempt to call predict using a dataset without the inference column.

Doing this by hand yields a regressor that works but doing this in a unit test does.  Some extra context:
```clojure
    (println thawed-model)
    (println (.formula thawed-model))
    (println (.toString df))
    (println (.predict thawed-model (.get df 0)))
```
yields
```clojure

#object[smile.regression.GradientTreeBoost 0x23dbb0d smile.regression.GradientTreeBoost@23dbb0d]
#object[smile.data.formula.Formula 0x2e765f21 y ~ .]
[x: double]
+---------+
|        x|
+---------+
|-0.992796|
|-0.982757|
|-0.972717|
|-0.962678|
|-0.952638|
|-0.942598|
|-0.932559|
|-0.922519|
| -0.91248|
| -0.90244|
+---------+
190 more rows...
<exception>
           StructType.java:   81  smile.data.type.StructType/fieldIndex
             Variable.java:  129  smile.data.formula.Variable/bind
              Formula.java:  219  smile.data.formula.Formula/bind
              Formula.java:  320  smile.data.formula.Formula/x
    GradientTreeBoost.java:  312  smile.regression.GradientTreeBoost/predict
```

**Additional context**
- openJDK 8
- 2.4.0
- Ubuntu

**Comment by cnuernber** [comment] 2020-06-05 22:22
More condensed example:
```clojure

tech.libs.smile.regression> test-ds
_unnamed [2 2]:

| :x | :y |
|----|----|
|  1 |  2 |
|  2 |  3 |
tech.libs.smile.regression> new-ds
_unnamed [2 1]:

| :x |
|----|
|  1 |
|  2 |
tech.libs.smile.regression> (def test-formula (Formula. "y"))
#'tech.libs.smile.regression/test-formula
tech.libs.smile.regression> (.x test-formula (.get (ds/dataset->smile-dataframe 
                                              new-ds)
                                                   0))
Execution error (NullPointerException) at smile.data.type.StructType/fieldIndex (StructType.java:81).
null
tech.libs.smile.regression> (.x test-formula (.get (ds/dataset->smile-dataframe 
                                              test-ds)
                                                   0))
#object[smile.data.formula.Formula$2 0x8e3b546 "{\n  x: 1\n}"]
tech.libs.smile.regression> (.x test-formula (.get (ds/dataset->smile-dataframe 
                                              new-ds)
                                                   0))
#object[smile.data.formula.Formula$2 0x56e15076 "{\n  x: 1\n}"]
tech.libs.smile.regression> 
```

-- I definitely did not expect side effects from evaluating formulas.

**Comment by cnuernber** [comment] 2020-06-05 23:02
Workaround:
https://github.com/techascent/tech.ml/blob/smile-integration-2/src/tech/libs/smile/protocols.clj#L18

**Comment by haifengl** [comment] 2020-06-06 01:34
There are a lot of considerations in this design to achieve a good balance between performance and flexibility. In short, Formula is abstract and independent of a particular DataFrame. When you train a model, the formula will bind to the schema of training data frame. For performance reason, we cache this binding as it is costly. When you apply the model to a new data frame (may have extra fields or different column ordering), the formula should be bound to the new schema. This will be done automatically when the saved model is loaded in a new process. And model.test() does that too.

Since the new data may have different schema, model.predict(DataFrame) to forcefully bind to the new schema. Note that model.predict(Tuple) won't do so to avoid the overhead.

**Comment by cnuernber** [comment] 2020-06-06 02:08
I would much rather use model.predict(DataFrame), that is very helpful, thank you.  

I understand columns can change their ordering.   That isn't the issue. 

The issue specifically is that when running from a new formula or a formula saved to disk.

Formula.bind *fails* for DataFrames that *do not* have the target, specifically [exactly this code](https://github.com/haifengl/smile/blob/master/data/src/main/java/smile/data/formula/Formula.java#L214) cannot work for dataframes that do not include the response which is every inference DataFrame. 

```clojure
tech.libs.smile.regression> (def ds (ds/->dataset (->> (range 100)
                                                       (map (fn [idx]
                                                              {:x idx
                                                               :y (* 2 idx)}))
                                                       )))
#'tech.libs.smile.regression/ds
tech.libs.smile.regression> ds
_unnamed [100 2]:

| :x | :y |
|----|----|
|  0 |  0 |
|  1 |  2 |
|  2 |  4 |
|  3 |  6 |
|  4 |  8 |
|  5 | 10 |
|  6 | 12 |
tech.libs.smile.regression> (def model (GradientTreeBoost/fit (Formula. "y")
                                                              (ds/dataset->smile-dataframe
                                                               ds)
                                                              (Properties.)))
#'tech.libs.smile.regression/model
tech.libs.smile.regression> (def bytes (model/model->byte-array model))
WARNING: bytes already refers to: #'clojure.core/bytes in namespace: tech.libs.smile.regression, being replaced by: #'tech.libs.smile.regression/bytes
#'tech.libs.smile.regression/bytes
tech.libs.smile.regression> (def hydrated-model (model/byte-array->model bytes))
#'tech.libs.smile.regression/hydrated-model
tech.libs.smile.regression> (def formula (.formula hydrated-model))
#'tech.libs.smile.regression/formula
tech.libs.smile.regression> (.schema formula)
nil
tech.libs.smile.regression> ;;for inference, we do not have the target column...
tech.libs.smile.regression> (def infer-ds (ds/remove-column ds :y))
#'tech.libs.smile.regression/infer-ds
tech.libs.smile.regression> (.x formula (ds/dataset->smile-dataframe infer-ds))
Execution error (NullPointerException) at smile.data.type.StructType/fieldIndex (StructType.java:81).
null
```
So, saving a model to a byte array using java serialization removes the schema from the formula.  Subsequently attempting to infer using the a model created from the byte array fails because of the above code:
```clojure
tech.libs.smile.regression> (type model)
smile.regression.GradientTreeBoost
tech.libs.smile.regression> (.schema (.formula model
                                               ))
#object[smile.data.type.StructType 0x33e8c547 "[y: long, x: long]"]
tech.libs.smile.regression> (def byte-data (model/model->byte-array model))
#'tech.libs.smile.regression/byte-data
tech.libs.smile.regression> (def new-model (model/byte-array->model byte-data))
#'tech.libs.smile.regression/new-model
tech.libs.smile.regression> (.schema (.formula new-model))
nil
``` 
Specifically [line 219 in Formula.java](https://github.com/haifengl/smile/blob/master/data/src/main/java/smile/data/formula/Formula.java#L219) fails if the formula does not already have a schema.  After GradientTreeBoost::fit the resulting model's formula does *not* have a schema and thus predict later fails if the inference dataset doesn't have the response.

**Comment by uriloya** [comment] 2020-06-22 07:10
Hi,
I had the exact same issue when deserializing a RandomForest class, the schema became null and prevented me from using the predict(Tuple x) method in regression/RandomForest.
(Tuple xt = formula.x(x); resulted in NPE).

The workaround I used was:
`for (RegressionTree tree : randomForest.trees()) {`
		`	y += tree.predict(X.get(0));`
	`	}`
	`	final double prediction = y / randomForest.trees().length;`

which is basically the predict(Tuple x) method with the first line removed

**Comment by haifengl** [comment] 2020-07-23 02:49
It is fixed in 2.5.0. Please have a try.

**Comment by Brandonage** [comment] 2020-07-24 11:27
I have this same problem. Basically I serialize a RandomForest object like so:

`try (final ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
    try (final ObjectOutput out = new ObjectOutputStream(baos)) {
        out.writeObject(randomforest);
        out.flush();
        return baos.toByteArray();
    }
}`

where randomforest is the actual object. When I deserialise it the formula part of the object has its schema, x, xschema and xy attributes as null and fails when using the predict method by creating a Dataframe

`rfSmileModel.predict(DataFrame.of(new double[][]{vector}))[0];`

I'll try with the new version

**Comment by Brandonage** [comment] 2020-07-24 12:39
Can't tell if its working or not because now it's not a serialisation problem. The problem now is that after training the binding attribute of the RandomForest has x, as null. I'm not sure if the fitting process is correct. Here is how I do it.

```
            // prepare data for Smile2.0 DataFrame Class
            final double[][] trainDataConcat = Smile2Utils.concatArrays(trainx, trainy);
            final String[] trainDataColNames = Smile2Utils.getDataFrameColumnNames(trainx[0].length, true);
            final String[] XColNames = Smile2Utils.getDataFrameColumnNames(trainx[0].length, false);
            final DataFrame trainDataFrame = DataFrame.of(trainDataConcat, trainDataColNames);
```

**Comment by haifengl** [comment] 2020-07-25 13:59
@Brandonage it is not clear to what you are doing and what's the problem.

**Comment by Brandonage** [comment] 2020-07-26 21:16
You are right. That's just confusing. I opened a different issue to not hijack this one. It's #586

**Closed** 2020-07-30 01:36 UTC
