### ISSUE TITLE
smile.regression.RandomForest::predict() sometimes returns NaN for very few samples

### ISSUE THREAD

**Issue by tuxdna** [haifengl/smile#526] opened 2020-03-22 11:08 UTC
## Expected behaviour

I train a RandomForest regression model on my data which has ~ 3000 samples and 8 attributes, all attributes are double precision, with the predicted value being a double in the range 0 to 1 in the training dataset. After traning, when we make predict() call on all the samples from training data, sometimes one or two samples result in NaN, instead of a valid double prediction.

## Actual behaviour

```
Found NaN
sampleNumber: 582
trueValue: 1.0
predictedValue: NaN
trueValue - predictedValue: NaN 

features: [17.0, 3.0, 0.058823529411764705, 0.7647058823529411, 1.5176745294625686, 0.19293206793206796, 1.0, 1.0]

```

## Code snippet

```java
        int numTrees = 25;
        int nodeSize = 1;
        int maxDepth = 20;
        double sampleRate = 0.85;

        Properties props = new Properties();
        props.setProperty("smile.random.forest.trees", numTrees + "");
        props.setProperty("smile.random.forest.node.size", nodeSize + "");
        props.setProperty("smile.random.forest.max.depth", maxDepth + "");
        int maxLeafNodes = trainDataSet.size() / 3;
        props.setProperty("smile.random.forest.max.nodes", maxLeafNodes + "");
        props.setProperty("smile.random.forest.sample.rate", sampleRate + "");
        RandomForest rf = RandomForest.fit(formula, trainDataSet, props);
```

## Input data

The data is described above. Can't share the actual dataset.

## Information

- Java 

```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

- Smile version 2.2.2
-  Ubuntu 18.04 64bit

**Comment by tuxdna** [comment] 2020-03-22 11:20
On debugging the code, of all the RegressionTree instances in the forest ( obtained via tf.trees() ), one RegressionTree predict()'s a NaN value. This apparently happens because the path traversed on this tree doesn't correspond to any samples from training data i.e. the LeafNode -- new RegressionNode(n, out, mean, rss) will mean of NaN.

So a quick fix could be to just ignore this prediction and return  a mean of remaining RegressionTree's predictions:

```diff
diff --git a/core/src/main/java/smile/regression/RandomForest.java b/core/src/main/java/smile/regression/RandomForest.java
index 5afc9817..e344147c 100644
--- a/core/src/main/java/smile/regression/RandomForest.java
+++ b/core/src/main/java/smile/regression/RandomForest.java
@@ -366,11 +366,16 @@ public class RandomForest implements Regression<Tuple>, DataFrameRegression {
     public double predict(Tuple x) {
         Tuple xt = formula.x(x);
         double y = 0;
+        int nanCount = 0;
         for (RegressionTree tree : trees) {
-            y += tree.predict(xt);
+            double p = tree.predict(xt);
+            if(Double.isNaN(p)) {
+                nanCount ++ ;
+            } else {
+                y += p;
+            }
         }
-        
-        return y / trees.length;
+        return y / (trees.length - nanCount);
     }
 
     /**
```

**Comment by haifengl** [comment] 2020-03-22 14:57
Thanks for reporting the problem. Can you share the tree and the sample that make NaN? You can do a `System.out.println(tree)`. I would like to find the root cause rather than a workaround.

**Comment by haifengl** [comment] 2020-03-23 12:57
Your nodeSize (1) is too small. Try 5.

**Comment by tuxdna** [comment] 2020-03-24 12:52
@haifengl When I try nodeSize=5, the precision drops significantly. Is there any way to prune those nodes which correspond to zero samples ?

**Comment by haifengl** [comment] 2020-03-24 13:01
- nodeSize = 1 generally overfits the data. Instead of reducing nodeSize, you should increase your sample size (300 is quite small).

- Please print the tree with zero-sample leaf. It should not happen. I would like to find out why.

**Comment by tuxdna** [comment] 2020-03-24 13:44
Actually the dataset contains 3000 ( 3k ) samples. Updated the description above.

Following file contains the the print()'ed version RegressTree causing NaN value on a sample ( also present in the file below ):

[smile-rfr-nan.txt](https://github.com/haifengl/smile/files/4375554/smile-rfr-nan.txt)

**Comment by haifengl** [comment] 2020-03-24 13:50
Some of your y are NaN. Note that the output of root is NaN. Otherwise, we should not get leaf of zero samples. Check how you read the data.

**Comment by tuxdna** [comment] 2020-03-24 14:41
I checked that there are no NaN / empty values for output variable.

Here is code and data that reproduces the issue: https://gist.github.com/tuxdna/c74befa1a9f85f0ed2ba4eaf2ad7263c/

**Comment by haifengl** [comment] 2020-03-25 19:21
Thanks for the data. I reproduce the problem with your data. The root cause that you have many values very close to each other such that floating number comparison is not stable. I harden the code to handle this case. The fix is in the master branch now.

**Comment by haifengl** [comment] 2020-03-25 19:23
BTW, you can run these two lines to train your model in smile shell:

```
val data = read.csv("randomized_train.csv", delimiter=',', header = true)

val rf = smile.regression.randomForest("A"~, data, ntrees = 25, mtry = 3, nodeSize = 1, maxDepth = 50, subsample = 0.85)
```

It is in scala. But you can do similar in Java. Check our website for examples.

**Comment by haifengl** [comment] 2020-03-25 19:25
Lastly, your hyperparameters are far from optimal for random forest. As said before, small nodeSize will overfit the data. Don't be fooled by the lower training error with nodeSize = 1. Similarly, maxDepth is too high (try < 20 given you have only a few variables). Lastly, ntrees should be much large (try 500, at least 200).

**Comment by tuxdna** [comment] 2020-03-26 10:50
@haifengl Thanks for fixing the issue and also suggesting a nicer way to load-csv/train the model.

Any idea when will the next release 2.3.0 or 2.2.3 will be available (hopefully containing this fix)?

**Comment by rayeaster** [comment] 2020-03-26 15:35
> Thanks for the data. I reproduce the problem with your data. The root cause that you have many values very close to each other such that floating number comparison is not stable. I harden the code to handle this case. The fix is in the master branch now.

@haifengl there maybe some issue for the assertions you add in the harden fix. guess it is due to the regression split do not use the `MathEx.isZero` for the predicate in its constructor (https://github.com/haifengl/smile/blob/master/core/src/main/java/smile/regression/RegressionTree.java#L223). It might cause mismatch in some tricky situation, i.e., one of the assertion would fail.

However, even after I comment out the assertions, similar NaN error would throw.

Test data and code to reproduce error as following:
https://github.com/haifengl/smile/blob/5880ddb62fe5b611f57389d1894583db6c505058/core/src/test/java/smile/data/CervicalCancer.java
https://github.com/haifengl/smile/blob/5880ddb62fe5b611f57389d1894583db6c505058/core/src/test/java/smile/regression/TreeShapTest.java

**Comment by haifengl** [comment] 2020-03-27 16:37
@rayeaster you have missing values in NHANES data.

BTW, you can do this to merge your X and Y files into one

```
paste -d, NHANESI_subset_y.csv NHANESI_subset_X.csv |cut -d, -f2,4-21 > NHANESI_subset.csv
```

Then you can read it easily with `Read.csv`, which will infer the data type.

**Comment by haifengl** [comment] 2020-04-01 13:06
@tuxdna 2.3.0 is out.

**Closed by haifengl** 2020-04-01 13:06 UTC
Labels: bug

**Comment by tuxdna** [comment] 2020-04-01 14:15
@haifengl That's awesome, thank you!
