### ISSUE TITLE
Build failure in current master (commit 296c29fdee887e7e8df98b7dfb5b812f02394937)

### ISSUE THREAD

**Issue by MenschNestor** [haifengl/smile#425] opened 2019-04-23 14:35 UTC
## Expected behaviour

`sbt package` is successful

## Actual behaviour

`sbt package` fails to compile with:

```
[error] /[...]/smile/core/src/main/java/smile/classification/RandomForest.java:182:1: ';' expected
[error]             this.mtry = (int) Math.floor(Math.sqrt(attributes.length))
```

## Information

- Oracle JDK 1.8.0_202
- Current master (commit 296c29fdee887e7e8df98b7dfb5b812f02394937)
- Mac OS X

**Comment by haifengl** [comment] 2019-04-24 18:46
It is caused by a recent pull request. It is fixed now. Thanks.

**Closed by haifengl** 2019-04-24 18:46 UTC
